// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4947.robot2015;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.CounterBase.EncodingType; import edu.wpi.first.wpilibj.PIDSource.PIDSourceParameter;
import edu.wpi.first.wpilibj.can.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static DigitalInput driveTrainAntennaLeft;
    public static DigitalInput driveTrainAntennaRight;
    public static Gyro driveTrainGyro;
    public static DigitalInput driveTrainLimitSwitchtest;
    public static CANJaguar driveTrainMotorRearLeft;
    public static CANJaguar driveTrainMotorFrontLeft;
    public static CANJaguar driveTrainMotorFrontRight;
    public static CANJaguar driveTrainMotorRearRight;
    public static RobotDrive driveTrainRobotDrive;
    public static SpeedController conveyorMotor;
    public static DigitalInput conveyorLimitSwitchLeft;
    public static DigitalInput conveyorLimitSwitchRight;
    public static CANJaguar conveyorElevatorMotorMaster;
    public static CANJaguar conveyorElevatorMotorSlave;
    public static Encoder conveyorElevatorEncoder;
    public static DigitalInput conveyorElevatorEncoderReset;
    public static Solenoid conveyorElevatorReleaseHook;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainAntennaLeft = new DigitalInput(2);
        LiveWindow.addSensor("DriveTrain", "AntennaLeft", driveTrainAntennaLeft);
        
        driveTrainAntennaRight = new DigitalInput(3);
        LiveWindow.addSensor("DriveTrain", "AntennaRight", driveTrainAntennaRight);
        
        driveTrainGyro = new Gyro(0);
        LiveWindow.addSensor("DriveTrain", "Gyro", driveTrainGyro);
        driveTrainGyro.setSensitivity(0.007);
        driveTrainLimitSwitchtest = new DigitalInput(0);
        LiveWindow.addSensor("DriveTrain", "Limit Switch test", driveTrainLimitSwitchtest);
        
        driveTrainMotorRearLeft = new CANJaguar(2);
        
        
        driveTrainMotorFrontLeft = new CANJaguar(4);
        
        
        driveTrainMotorFrontRight = new CANJaguar(7);
        
        
        driveTrainMotorRearRight = new CANJaguar(3);
        
        
        driveTrainRobotDrive = new RobotDrive(driveTrainMotorFrontLeft, driveTrainMotorRearLeft,
              driveTrainMotorFrontRight, driveTrainMotorRearRight);
        
        driveTrainRobotDrive.setSafetyEnabled(true);
        driveTrainRobotDrive.setExpiration(0.1);
        driveTrainRobotDrive.setSensitivity(0.5);
        driveTrainRobotDrive.setMaxOutput(1.0);

        conveyorMotor = new Talon(0);
        LiveWindow.addActuator("Conveyor", "Motor", (Talon) conveyorMotor);
        
        conveyorLimitSwitchLeft = new DigitalInput(4);
        LiveWindow.addSensor("Conveyor", "LimitSwitchLeft", conveyorLimitSwitchLeft);
        
        conveyorLimitSwitchRight = new DigitalInput(10);
        LiveWindow.addSensor("Conveyor", "LimitSwitchRight", conveyorLimitSwitchRight);
        
        conveyorElevatorMotorMaster = new CANJaguar(8);
        
        
        conveyorElevatorMotorSlave = new CANJaguar(5);
        
        
        conveyorElevatorEncoder = new Encoder(5, 6, false, EncodingType.k4X);
        LiveWindow.addSensor("ConveyorElevator", "Encoder", conveyorElevatorEncoder);
        conveyorElevatorEncoder.setDistancePerPulse(1.0);
        conveyorElevatorEncoder.setPIDSourceParameter(PIDSourceParameter.kRate);
        conveyorElevatorEncoderReset = new DigitalInput(7);
        LiveWindow.addSensor("ConveyorElevator", "EncoderReset", conveyorElevatorEncoderReset);
        
        conveyorElevatorReleaseHook = new Solenoid(0, 0);
        LiveWindow.addActuator("ConveyorElevator", "ReleaseHook", conveyorElevatorReleaseHook);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
