// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4947.robot2015.commands;

import org.usfirst.frc4947.robot2015.Robot;

import edu.wpi.first.wpilibj.command.Command;

/**
 *
 */
public class  ConveyorIn extends Command {
	private boolean isEmpty = false;
	
    public ConveyorIn() {
        requires(Robot.conveyor);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	Robot.conveyor.setSpeed(-1);
    	Robot.conveyor.setGreenLight(true);
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	
    	if(Robot.conveyor.getLimitSwitchLeft() && Robot.conveyor.getLimitSwitchRight()){
    		isEmpty = true;
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	return isEmpty && !Robot.conveyor.getLimitSwitchLeft() && !Robot.conveyor.getLimitSwitchRight();
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.conveyor.setSpeed(0);
    	Robot.conveyor.setGreenLight(false);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	end();
    }
}
